name: sql_money
description: a class to work with numbers in the same way as ms-sql Money datatype as a 4dp constrained datatype for financial accuracy
version: 1.0.3
homepage: https://github.com/KyleyHarris/sql-money

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
