name: sql_money
description: this library contains an SqlMoney class which works in the same way as MS-SQL Money DataType and
Delphi native Currency type, being a double style value constrained to 4dp and intended for use in financial 
application. internally stored as bigint, after rounding and using a multiplier to remove inaccuracies of the 
double type
version: 1.0.1
homepage: https://github.com/KyleyHarris/dart-currency

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
